export const genre = [
  "Fantasy",
  "Science Fiction",
  "Mystery",
  "Romance",
  "Thriller",
  "Horror",
  "Historical Fiction",
  "Dystopian",
  "Adventure",
  "Crime Fiction",
  "Young Adult (YA)",
  "Children's Literature",
  "Biography",
  "Non-fiction",
  "Self-help",
  "Poetry",
  "Graphic Novel / Comic",
  "Satire",
  "Classic Literature",
  "Contemporary Fiction",
  "Paranormal",
  "Steampunk",
  "Urban Fantasy",
  "Cyberpunk",
  "Gothic Fiction",
  "Memoir",
  "Science Non-fiction",
  "Biography",
  "Western",
  "Humor/Comedy",
];
